# This file was automatically generated by apk2nix on Tue Aug 14 11:32:04 CEST 2018
# Command: /nix/store/2zbqzd3qzl97kjwkib4qiv5wia2cn5ks-apk2nix/bin/apk2nix -o alpine/systems/alpine-sdk.nix alpine-base alpine-sdk
[

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/cryptsetup-libs-1.7.5-r1.apk
  ; sha256 = "0gw5d87yzdzzrdj3fwqqnwjn2d2khczjk9wl66kplz0q3lsksrxk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/zlib-1.2.11-r1.apk
  ; sha256 = "124m1ncl7rs48dp5pa35a831fvgh322b554vmfqm3jpddawgv4ql"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/device-mapper-libs-2.02.175-r0.apk
  ; sha256 = "0p7g167caap7p2cmhjia39njkcdb825yfk63zv1m63jjgsz0si5c"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libburn-1.4.8-r0.apk
  ; sha256 = "0ijcgpq3x5dmimwcc2av5b54h6fpxvm6lnapwz8m3p5q2afabr2m"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/lz4-libs-1.8.0-r1.apk
  ; sha256 = "1vl0a0mhsjvl4172ss36gv5f96dla9gjpdi2z3ksc834dlijx0mm"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/binutils-libs-2.30-r1.apk
  ; sha256 = "0azyzbp8fxjzw6p4afc4irlwc156h4xprsqllpwz8lm205650pr7"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libstdc++-6.4.0-r5.apk
  ; sha256 = "0l5jfbn9kcvjw6miy4gbzgfnfz2injkqvq7dqv7v30ydcnfx4i6n"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libressl2.6-libssl-2.6.5-r0.apk
  ; sha256 = "1xkvzhr1bwicj76ffsvzmpz2440ani03dgm70c10sxhhhaaqdq1s"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/sudo-1.8.21_p2-r1.apk
  ; sha256 = "05hvrq3gvmhinpnhfi7lkjb5rrig3pdplq8v5w4c7rhyhr7ch0pb"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libcap-2.25-r1.apk
  ; sha256 = "1qgxygn3l59adgp4kxdmsgwvd2vywmkz4k3v739y09k5vvdsf2z4"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/ncurses-libs-6.0_p20171125-r0.apk
  ; sha256 = "13dhm8vr2h7dyv3h4sm234p322afgjrq7n2i9liiwk6q1dkbyjks"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libssh2-1.8.0-r2.apk
  ; sha256 = "1h52xb3pxb877js05l2n4lpfnwmsslrdikxy7f13bqwnmnp6xf9b"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/musl-dev-1.1.18-r3.apk
  ; sha256 = "0vrd7p9jqb4xcf7izidx0bz15m16rp76s44a62nl6ijvv9h7npq1"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libatomic-6.4.0-r5.apk
  ; sha256 = "0wgggybgf6wf3nm8v1i1775ny30yyn3qvvrz0xa3yjn92la6hxn7"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libressl-2.6.5-r0.apk
  ; sha256 = "0n7mws92s5z58jq19h29gqc28ydpm00dk7gzqf68mmnjnl136fyv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-conf-3.7.0-r1.apk
  ; sha256 = "1qcd9a31ikrr2cr8liw4xa5xkxqzjwf39pwlqqd70w4xgpkpcnl6"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/ncurses-terminfo-6.0_p20171125-r0.apk
  ; sha256 = "18wnxcrcwxdf9r1z3cda4i2r98nyy88dkvsli1sx3lvavivrrhdp"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/busybox-initscripts-3.1-r2.apk
  ; sha256 = "0qdhq7v8bqkcfkg6d53gkbylx1g0vpkdbxbf0497vq7fmdmzsz73"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libcurl-7.61.0-r0.apk
  ; sha256 = "1ag0abr90yfwqqvqlw74nzisl1hwj8g1af8ym5x1s06frdwpj0xr"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libisoburn-1.4.8-r0.apk
  ; sha256 = "0rgmjsrbqfbgb77kwbm6rk7jq4kns91jn96a5b41nk0jqzx2jbwv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libacl-2.2.52-r3.apk
  ; sha256 = "0qh6aw1np4bazkvy78syxrhk0kcshqxlgs803r7bbvz5p5f5h10g"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/pax-utils-1.2.2-r1.apk
  ; sha256 = "1vygsjiin2h05gadb0qn64axiy8ifbz573x5bc1hg2l6qhs427rk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libattr-2.4.47-r6.apk
  ; sha256 = "0yd7y899aygkwqis03c80w3gq3gb8jj8hx3pr8j7g8qyj5qgl9sl"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/squashfs-tools-4.3-r4.apk
  ; sha256 = "1489ki0f1ikfyy5f177aqzj25nvsf864xkqhrfc96k42cn2a5gwy"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libedit-20170329.3.1-r3.apk
  ; sha256 = "10bn7a5xv1g3w755qcdks5xnmzr39zf01kbpxnrnsb6caw48r2xx"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/binutils-2.30-r1.apk
  ; sha256 = "0dsdy2vwrinx1mwrmvy6xgxhmblc2x3yvbx2apriq40qwdxrrzps"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/busybox-suid-1.27.2-r11.apk
  ; sha256 = "06v9g8f2dlngnfqxrk6n7pjr4i8fgi5y80f49g76dfwp2bz93s3r"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libuuid-2.31-r0.apk
  ; sha256 = "08cmxfrkbb5r217qcag2frp70knck7ncxi484ab95xm5vaw7qwhk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/fakeroot-1.21-r1.apk
  ; sha256 = "194zfrfys05mydq9zld93vn7czxknrq2f5d54mfm18r11b7lkrza"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/build-base-0.5-r0.apk
  ; sha256 = "0n8dyzcyi8mpz3ma3gpzp4fpx6q7l4pdplnia4spiv8782rp9snr"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mpfr3-3.1.5-r1.apk
  ; sha256 = "0hfqan488aa1bsqr67p99d3ph53srdqk5sa9zdb5fay2s98jd76k"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/isl-0.18-r0.apk
  ; sha256 = "1y0zcrlw46jw1j49530ddb49c5phxsi6vfk049kzwd60058ljal1"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/attr-2.4.47-r6.apk
  ; sha256 = "1iixvaxhkk15lqn94v6vlh0qp4j1srpw2ppfaf0gf9z9k7174knc"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/ca-certificates-20171114-r0.apk
  ; sha256 = "1l5cazi2hdzzn3qkn1g9gglnqf51drrd1ai46dbw6n6qy9ysx3b1"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/busybox-1.27.2-r11.apk
  ; sha256 = "1b37bil28gpnb8p4wzlw08a9i82ajckzq1nm7n9xw3npyfqvlbv6"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-sdk-0.5-r0.apk
  ; sha256 = "0jlyya8f7nrmh18c3vfb9czw8slsjq4cg0r7b122ccnblzaizxip"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libgomp-6.4.0-r5.apk
  ; sha256 = "1i71h1cvlvr7mgy1fy349f3ch6ci5msqyrisn2fyfgc2wbk4l26n"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libc-dev-0.7.1-r0.apk
  ; sha256 = "0314yv8llbx71cwivyyv7cn9q9izb5ap4xj9aw25xlibq860y95m"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-base-3.7.0-r0.apk
  ; sha256 = "05k25lwa2l2gn1wiiqgb7sgrwrn2biccixqjn6ppkcilbwsw4v7l"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/musl-utils-1.1.18-r3.apk
  ; sha256 = "1yvcjr2rc8yl85y9r5pyyywdpv1nb8i6qizslf5h2ij2nm26ywid"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/musl-1.1.18-r3.apk
  ; sha256 = "1vjj1kjqwldd313k74qczy3vslrfhpbgyycx1qfys8jbcdf2wljk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/gcc-6.4.0-r5.apk
  ; sha256 = "073c1v95y24pvqrm1b15jm3h02bakciy7h4a13rqx4pxx0hmgypd"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xorriso-1.4.8-r0.apk
  ; sha256 = "1i0r8q539z3x07cgz6b9wma31s3a20i2amg9q6hj1269cr5zl3f6"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/abuild-3.1.0-r4.apk
  ; sha256 = "08km252gxd4bsk1pjs3ivsndbnjs5iigij8l4h5mgq5wnxxi480a"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/lzip-1.19-r1.apk
  ; sha256 = "158sd62iw9gbli40h5j7z6p2k9xvlq68f2njss8hvlywxk9zg586"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mtools-4.0.18-r2.apk
  ; sha256 = "0a88vwb3km0kmyrnls49p0h4vzz3r4kn48wm9ajk2rvdzi6x4j6h"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xz-libs-5.2.3-r1.apk
  ; sha256 = "19axnwgmfmcb9csc8yss2dqy7i35za2gcmq9v7610k8rzprdj0gl"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libressl2.6-libtls-2.6.5-r0.apk
  ; sha256 = "15xcda4y4563nw0zckl4wvgv5x5syr69jf9cnpk4ikd7mh4kyffk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libisofs-1.4.8-r0.apk
  ; sha256 = "1xjbgjxc3w5a3mca7kp56k8y92m0qca3z3zizkq12s7crk31j4qh"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-baselayout-3.0.5-r2.apk
  ; sha256 = "1pxh2kmsj8zn92wh4kpsi1lk3314glwinrihqi4zrs91qn81bdi0"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/patch-2.7.5-r2.apk
  ; sha256 = "1rylsy2asrl7kza8rljfdqi1w9k0yb4dgqs29rnzimvbdpklzgwr"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libblkid-2.31-r0.apk
  ; sha256 = "0a99187bns2mvrj7gk107j0nddzhc4cmxryr2pk9412jman8kpgd"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/kmod-24-r0.apk
  ; sha256 = "1giglgrlypydcy8sch7rlv7mdg13q6kwlbhyfqddqqxxzlma3pj3"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/pkgconf-1.3.10-r0.apk
  ; sha256 = "16rsg27inryscvjll2y05vj9snp7c5irz1v8w7lbmri2ph9vf167"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/acct-6.6.4-r0.apk
  ; sha256 = "1chkjaiqi6lm1zshn6v8d7z53fh4by4pgw1kz0w3l2j2d6gswz1p"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/apk-tools-2.9.1-r2.apk
  ; sha256 = "1cyx15677xx7m37frqs6aa7iqn1g34wmpasa7yi3b1djdrvq19yv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libgcc-6.4.0-r5.apk
  ; sha256 = "1146gmvgyykq3whfypzm9y424zis12myflxxca3l7fmzq2zilwv2"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/git-2.15.2-r0.apk
  ; sha256 = "1i48qhbv54i5h7icvqdahki7ppasw8ns7fwb50p1gd5jnyqhi10l"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/make-4.2.1-r0.apk
  ; sha256 = "1c17bnfaxz5ygibbx67mmjg1gg5mrdyvkk8bv752br1m3xx0xv94"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/curl-7.61.0-r0.apk
  ; sha256 = "0nfifhpmz586wm356rk7kks1panka4m5dv9v5mcrixlzfhid6j30"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/scanelf-1.2.2-r1.apk
  ; sha256 = "1n6s8grkskia2bfxy94bkhnvcqp0bm2m3n6lnwiq49rl3aa3myhl"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/lddtree-1.26-r1.apk
  ; sha256 = "1z1fpx9xjp4fcqlk4acm5wsng4gg9v5vd8rkvspk5fydyhyqdclw"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/gmp-6.1.2-r1.apk
  ; sha256 = "1m09sf5yifp816cv3yk4j4gqg8z2rb73fp9qxb759gyf3gc14i40"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/pcre2-10.30-r0.apk
  ; sha256 = "1hxk9sqq6haamxks1i2h5r3v179xssgmm4kamqmv7d4d10spd0g8"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libc-utils-0.7.1-r0.apk
  ; sha256 = "19gv1vhvjd0lzyjzqdq1j04cjz5kq9warak349jvk0932yb3j74l"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/openrc-0.24.1-r4.apk
  ; sha256 = "0r7qsbjljhxgdkgrcqsl8jal7y75dwjcim2kf9l7gdbinsnvrca3"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/ncurses-terminfo-base-6.0_p20171125-r0.apk
  ; sha256 = "0vrm0538davp54irspb4140k5fbsxgyads827ng79ipg788akdd2"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/lzo-2.10-r2.apk
  ; sha256 = "0fh8i5d5lrvaym8441lr19riqilh4d36dfzwg7nwa8zghfl76yhm"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/g++-6.4.0-r5.apk
  ; sha256 = "0wz28drwkfc8hivdiy8d9714kc25b7zxkya9j0kzh0slwfg861py"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/expat-2.2.5-r0.apk
  ; sha256 = "0gwysh56byffd4cmqa1pir5j24bwgiv03z2k8fn3yi30lyddc1ir"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libressl2.6-libcrypto-2.6.5-r0.apk
  ; sha256 = "1b8v18s054wqh54b0vwghcn52q01nzxfw3vi6ab0qaj6jywclzrs"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/ssl_client-1.27.2-r11.apk
  ; sha256 = "179cv4wmn6v1411v7wcazr1z9qiv9kz5q1p1q681v90h91rckn11"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/tar-1.29-r1.apk
  ; sha256 = "1lz9p55mcxbfzkbb84ljyrqyijsv6sya5cw2y733n55qa7jw7p57"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-keys-2.1-r1.apk
  ; sha256 = "1isw8wd7w0k2jyx76x77051560myaliw4pbq97p8wk1j02d1wbbv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mkinitfs-3.2.0-r4.apk
  ; sha256 = "0yi230xbvg4widh05ii1i9199nmrirw41qis4cb940rwrda5hhwa"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/fortify-headers-0.9-r0.apk
  ; sha256 = "1pm0zzccxzrffdlirlyfmr2kph01hkdsmnsv4v3lvsyj5iwmjfhg"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mpc1-1.0.3-r1.apk
  ; sha256 = "1hbj7pvk9casck8vqqhga52a155xn9kdd7a2rij29wc72vm9ap39"; }
]
