# This file was automatically generated by apk2nix on Fri Jul 13 18:27:42 CEST 2018
# Command: /nix/store/zfg7k43y33c7qfib8ck41j7a0x6w05yh-apk2nix/bin/apk2nix -o alpine/pkgs/alpine-base.nix alpine-base
[

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/zlib-1.2.11-r1.apk
  ; sha256 = "124m1ncl7rs48dp5pa35a831fvgh322b554vmfqm3jpddawgv4ql"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libressl2.6-libssl-2.6.5-r0.apk
  ; sha256 = "1xkvzhr1bwicj76ffsvzmpz2440ani03dgm70c10sxhhhaaqdq1s"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-conf-3.7.0-r1.apk
  ; sha256 = "1qcd9a31ikrr2cr8liw4xa5xkxqzjwf39pwlqqd70w4xgpkpcnl6"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/busybox-initscripts-3.1-r2.apk
  ; sha256 = "0qdhq7v8bqkcfkg6d53gkbylx1g0vpkdbxbf0497vq7fmdmzsz73"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/busybox-suid-1.27.2-r11.apk
  ; sha256 = "06v9g8f2dlngnfqxrk6n7pjr4i8fgi5y80f49g76dfwp2bz93s3r"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/busybox-1.27.2-r11.apk
  ; sha256 = "1b37bil28gpnb8p4wzlw08a9i82ajckzq1nm7n9xw3npyfqvlbv6"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-base-3.7.0-r0.apk
  ; sha256 = "05k25lwa2l2gn1wiiqgb7sgrwrn2biccixqjn6ppkcilbwsw4v7l"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/musl-utils-1.1.18-r3.apk
  ; sha256 = "1yvcjr2rc8yl85y9r5pyyywdpv1nb8i6qizslf5h2ij2nm26ywid"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/musl-1.1.18-r3.apk
  ; sha256 = "1vjj1kjqwldd313k74qczy3vslrfhpbgyycx1qfys8jbcdf2wljk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libressl2.6-libtls-2.6.5-r0.apk
  ; sha256 = "15xcda4y4563nw0zckl4wvgv5x5syr69jf9cnpk4ikd7mh4kyffk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-baselayout-3.0.5-r2.apk
  ; sha256 = "1pxh2kmsj8zn92wh4kpsi1lk3314glwinrihqi4zrs91qn81bdi0"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/apk-tools-2.9.1-r2.apk
  ; sha256 = "1cyx15677xx7m37frqs6aa7iqn1g34wmpasa7yi3b1djdrvq19yv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/scanelf-1.2.2-r1.apk
  ; sha256 = "1n6s8grkskia2bfxy94bkhnvcqp0bm2m3n6lnwiq49rl3aa3myhl"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libc-utils-0.7.1-r0.apk
  ; sha256 = "19gv1vhvjd0lzyjzqdq1j04cjz5kq9warak349jvk0932yb3j74l"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/openrc-0.24.1-r4.apk
  ; sha256 = "0r7qsbjljhxgdkgrcqsl8jal7y75dwjcim2kf9l7gdbinsnvrca3"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libressl2.6-libcrypto-2.6.5-r0.apk
  ; sha256 = "1b8v18s054wqh54b0vwghcn52q01nzxfw3vi6ab0qaj6jywclzrs"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/ssl_client-1.27.2-r11.apk
  ; sha256 = "179cv4wmn6v1411v7wcazr1z9qiv9kz5q1p1q681v90h91rckn11"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-keys-2.1-r1.apk
  ; sha256 = "1isw8wd7w0k2jyx76x77051560myaliw4pbq97p8wk1j02d1wbbv"; }
]
