# This file was automatically generated by apk2nix on Thu Jul 19 11:31:07 CEST 2018
# Command: /nix/store/2zbqzd3qzl97kjwkib4qiv5wia2cn5ks-apk2nix/bin/apk2nix -o nodm/makedeps.nix xorg-server libx11 autoconf automake libx11-dev linux-pam-dev linux-headers help2man
[

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/freetype-2.8.1-r3.apk
  ; sha256 = "0czpmascqh6i819v0w7qbqahylsqqkkv1arrdfynfdvpc72ylckg"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xmodmap-1.0.9-r2.apk
  ; sha256 = "0264y633q8j5zj54qglf5pmw3yz1ncxpqvskkn7fpghj6m8yf04x"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mesa-gbm-17.2.4-r1.apk
  ; sha256 = "0pli7f51aa3nk5c7rpgkhlqsnwy5j010mmll4a3p1jb59rqr4s3d"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/zlib-1.2.11-r1.apk
  ; sha256 = "124m1ncl7rs48dp5pa35a831fvgh322b554vmfqm3jpddawgv4ql"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxshmfence-1.2-r2.apk
  ; sha256 = "0f4jpw1qssdx96xlmdq3abvpm6x53fy53ibjw72k67g5gn7sfxi8"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libstdc++-6.4.0-r5.apk
  ; sha256 = "0l5jfbn9kcvjw6miy4gbzgfnfz2injkqvq7dqv7v30ydcnfx4i6n"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xrdb-1.1.0-r2.apk
  ; sha256 = "1gi2ad1dvprsbv6szdrk34v8nx60zld2kblii9ygsa1imqwc61a5"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/wayland-libs-client-1.14.0-r2.apk
  ; sha256 = "0jygqc89bmxhy9w765vrnp87mdk64pfdb13zyksz8sz0vh3658nv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/ncurses-libs-6.0_p20171125-r0.apk
  ; sha256 = "13dhm8vr2h7dyv3h4sm234p322afgjrq7n2i9liiwk6q1dkbyjks"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxcb-dev-1.12-r1.apk
  ; sha256 = "0y36lv1342dinfgzxc71dzrfmjm6m03q97l24m310fwina636zb1"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxt-1.1.5-r1.apk
  ; sha256 = "0kr5x8iyrkxcizws1v59kqz687xidhij7jk5q5b833any73kcynp"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/linux-pam-dev-1.3.0-r0.apk
  ; sha256 = "02n0ls56n9zd07r2ixgckxsf7j53z17jys6jk4r4drm7xnizaz8q"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libpng-1.6.34-r1.apk
  ; sha256 = "16hwbs98nkzsxw5722jxs61cnvqisgai0xqmvh673yx8ij6zqb4b"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libmount-2.31-r0.apk
  ; sha256 = "0wl89nfhvpddqx21lsq17d1iawkh14kcj14gxhhw5wp8mc9k2cnv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxfont2-2.0.3-r0.apk
  ; sha256 = "134v0rxk7my22s03qkkx1dfsii0838qnyis2vhaazlwi2wrgbv2k"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/wayland-libs-cursor-1.14.0-r2.apk
  ; sha256 = "0csypwmrg2lr3x2f9h4q572v3x2q3q9lprchnx8ggz1c89wln3xg"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/ncurses-terminfo-6.0_p20171125-r0.apk
  ; sha256 = "18wnxcrcwxdf9r1z3cda4i2r98nyy88dkvsli1sx3lvavivrrhdp"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/encodings-1.0.4-r1.apk
  ; sha256 = "0blx22js6amzwsy2vy5l4mq8jmw68wqapb67zfyrymp16d8wgzjr"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libice-1.0.9-r2.apk
  ; sha256 = "1nly41xif2nkiplgaakbvwnfbarkl4zfh1kmnrbj0pifmyj7spbn"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxfixes-5.0.3-r1.apk
  ; sha256 = "08ip4qzzdyfc9d6lhbl3nff1dqw7n23rvhmwy2cz9bbqiq2r779p"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxmu-1.1.2-r1.apk
  ; sha256 = "1sb9nj8hy8l404nnp84m8rpn1nl2pask5yl177rv2wq849lzg7xh"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libfontenc-1.1.3-r2.apk
  ; sha256 = "0dskr06246ycxgcasnrp34jj4sdi5a56zk820dz7zczkglivcf3v"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxdmcp-1.1.2-r4.apk
  ; sha256 = "0h28p3rzaccs17sdy8vd7mjb9n4501xc5vv3agphjipkrna16qij"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/kbproto-1.0.7-r2.apk
  ; sha256 = "1m5dd778l1dxb4yblch5zqclaqj72qhjg219djkxdcyzh6axcrmv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mcpp-2.7.2-r1.apk
  ; sha256 = "07jxc0hcdv30yymg9bvp1fq9pj8ads0ghr4k4z64ivj9yh61437l"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxml2-2.9.7-r0.apk
  ; sha256 = "1cyh5g95a69nlamr1wmcfqcik5w78w9dxkpr1473afj4m0z9blfd"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxcb-1.12-r1.apk
  ; sha256 = "0jdld4gqsla96grpczw1ihmz5jb4g228lby8hpbqh9401425hk50"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxau-1.0.8-r2.apk
  ; sha256 = "1nxv9bc0srdz0fz1lar0pnjm13bhhx9ajc7qw4fh88r8l46pbxlq"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/gettext-dev-0.19.8.1-r1.apk
  ; sha256 = "0v6qws2spmpb9vpm56v3hn9n9xdjbv27wbpc82djx5vrdk330kpz"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libx11-dev-1.6.5-r1.apk
  ; sha256 = "00b0ad5nhl4w2djw1b9fzf4sw2knwc0s06gha4qbkrmdn2iacg1g"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libffi-3.2.1-r4.apk
  ; sha256 = "0hh403fwv20lgl6dls63a53g5hi67pmjd3wrlvkphbii0vhi6nsr"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/m4-1.4.18-r0.apk
  ; sha256 = "1kqf141xw1mrx10qfiwl11q3hpz91glvfg9m03qjf4kp6d34l2zv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xproto-7.0.31-r1.apk
  ; sha256 = "0jjd562i0n03s7hh6m441mj8f0kc7npsf3q65c9zqpbs0ihw7pnf"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/font-cursor-misc-1.0.3-r1.apk
  ; sha256 = "1lvp29cm3bvn09xssbpqiivm5p637dw8xvkbi2m7m5nb4n1prhzc"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/inputproto-2.3.2-r1.apk
  ; sha256 = "1qcya6laf5w11397xzy98ljlvlwrdx7nshq7wv393wdqyd11qdxq"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/linux-headers-4.4.6-r2.apk
  ; sha256 = "18iczhypfcpblm6pdvj3rsvgjzldh1l5dcj8h5ammxlaalnjnadv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libbz2-1.0.6-r6.apk
  ; sha256 = "00d8sdnjam99690nsgq50ccx99kvxn9n8vvq97295n91fg4phd9b"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/font-misc-misc-1.1.2-r1.apk
  ; sha256 = "19sx5zdvmakpk4qavh3x18zavnvkap9ga1c7mb6rkswg21ss7kza"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxdamage-1.1.4-r1.apk
  ; sha256 = "0cam8g3z22gplbi1a7gy3wgx1m4s2ll080jmr8693cnyqhmkyvvc"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/eudev-libs-3.2.4-r1.apk
  ; sha256 = "1nzm8f3mp34pn6bpndmcpb2k4r05n8jv318hvs8gxixwxqy4n8dz"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mesa-gl-17.2.4-r1.apk
  ; sha256 = "0bfk290ra7g1ncjbx0nswh28f77b6xhrd9vvvswf9fi7fpdkppnd"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/automake-1.15.1-r0.apk
  ; sha256 = "05x5zifp3vrdbnajschirn1js57vczn4pw2qnvhc57k8cnx2j67c"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libuuid-2.31-r0.apk
  ; sha256 = "08cmxfrkbb5r217qcag2frp70knck7ncxi484ab95xm5vaw7qwhk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/perl-5.26.2-r1.apk
  ; sha256 = "1v09lgxa3kpk9xjk92n7ivf8qwnwjxc917r5sswimfvcifwcp9dp"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libepoxy-1.4.3-r1.apk
  ; sha256 = "1ryxqzgi7mina21b32x3695dgb7xgsgj8pzmpcsi615lv0rb7i0b"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxext-1.3.3-r2.apk
  ; sha256 = "1178sg2ahkdhh0w01kxj1k9i5z6i9m6iziv42a7hl4m2gs5yvyhp"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xauth-1.0.10-r1.apk
  ; sha256 = "1x9k4ahw96w6nwb29rsakz731sylifx9kbfnxhhaksmvi7wx7vxy"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/gettext-0.19.8.1-r1.apk
  ; sha256 = "0z0i2kd7vfynp5wyvfr07mjjnqiw4508ixh3zb28faa6rcxxi0cz"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libx11-1.6.5-r1.apk
  ; sha256 = "1f8amk5c6vby66b34swvbbjiw0cn5fxsr8yrn8594x3z1a1jm2z5"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/busybox-1.27.2-r11.apk
  ; sha256 = "1b37bil28gpnb8p4wzlw08a9i82ajckzq1nm7n9xw3npyfqvlbv6"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mesa-glapi-17.2.4-r1.apk
  ; sha256 = "1j4jdsn776pwb3s2gy3m545c7qvq0in9b52sjsvz5mw5mahx5lby"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libgomp-6.4.0-r5.apk
  ; sha256 = "1i71h1cvlvr7mgy1fy349f3ch6ci5msqyrisn2fyfgc2wbk4l26n"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/wayland-libs-server-1.14.0-r2.apk
  ; sha256 = "1kjywpyd83vmbhh0g898y95xb459psc7r8kjmzqyssr8lk07bjjz"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxau-dev-1.0.8-r2.apk
  ; sha256 = "0qlnwc84d6pshk4h0jj6xjvdlmvkzzpz41z2a5165sb61qnwx55l"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/musl-1.1.18-r3.apk
  ; sha256 = "1vjj1kjqwldd313k74qczy3vslrfhpbgyycx1qfys8jbcdf2wljk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/gettext-asprintf-0.19.8.1-r1.apk
  ; sha256 = "1b9ab9gyya4hgfsar98cyh6ymix19r6svin1w5mxi4kab6cwaa8i"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xorg-server-1.19.5-r0.apk
  ; sha256 = "0aiz8bkqpb8adyv9w56w0p1pd8q01lzj2arv507d31s329hswnlz"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/gettext-libs-0.19.8.1-r1.apk
  ; sha256 = "1xki69kg2gjdsfwwdm5d76y89h6f9zagl28lw5k9sniszblm6g00"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/linux-pam-1.3.0-r0.apk
  ; sha256 = "1n3jd68d7n0zhdw8gd60h1y0x52idwqrnah2qsswn3j65nyqn119"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mcpp-libs-2.7.2-r1.apk
  ; sha256 = "0s85935mf9kz02zd8v3rnffd7hmydarypjvf59qif03z171i17ab"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xf86bigfontproto-dev-1.2.0-r5.apk
  ; sha256 = "1sx9xmlkmgdlh1k2l4wxw6xqx98z5jcffp0v0r1b59x5gxgvrais"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxkbfile-1.0.9-r2.apk
  ; sha256 = "08wikv0zj83hnhgza6qyfg4b7x1qp27ciqali6g689sfj8s50k2n"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libsm-1.2.2-r1.apk
  ; sha256 = "0nq6cpxf4i5dmdhavl9wvm0w8wzc43wx573356qg5k1wpii2cj51"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xinit-1.3.4-r1.apk
  ; sha256 = "1arzaazxwn1y8f5nw5r87y22xanwcci4yvlr58gv3wx9iy2kh4nv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libblkid-2.31-r0.apk
  ; sha256 = "0a99187bns2mvrj7gk107j0nddzhc4cmxryr2pk9412jman8kpgd"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libpthread-stubs-0.3-r4.apk
  ; sha256 = "0adg0hrbz9my3y7lf72kmnzkgzrrg47bnnfxl6s2cw24v976z83v"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/pkgconf-1.3.10-r0.apk
  ; sha256 = "16rsg27inryscvjll2y05vj9snp7c5irz1v8w7lbmri2ph9vf167"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libcrypto1.0-1.0.2o-r1.apk
  ; sha256 = "02k67ih679y73zl5q6y54vdvwxlrcyvykjy23dyc5j2qqfzssah1"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/autoconf-2.69-r0.apk
  ; sha256 = "0v5wzfxf0cd8d4wgbb3ffs9lg3is4c21pf6k4l7n4v9cfdnr5zr1"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xkbcomp-1.4.0-r2.apk
  ; sha256 = "01f3xcy1lb90pcnxvzsnglbjr5wbfg1yz53f50nn2hni0k0jm1a8"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libpciaccess-0.13.5-r1.apk
  ; sha256 = "1akl82lgzmsm0kyck2bn1cf7a8x1xdcjxskf7wq7ddl8q7svzxgh"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/util-macros-1.19.1-r1.apk
  ; sha256 = "177y0yjxjk8ic2rd07dxykwqwxmra00lyv5wiz2m11sq60bhcgm3"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libbsd-0.8.6-r1.apk
  ; sha256 = "1q0kmb24i7x1s2ild9020phxin7xrvdh7ac5cjp2njdaz33m8qkg"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libgcc-6.4.0-r5.apk
  ; sha256 = "1146gmvgyykq3whfypzm9y424zis12myflxxca3l7fmzq2zilwv2"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libdrm-2.4.88-r0.apk
  ; sha256 = "1l407cjh9g8hd2ym4p2izga98q1lmh1hpr2rl6p53wpkdvpdbmr6"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/fontconfig-2.12.6-r0.apk
  ; sha256 = "012qyg30krky6x1wbcl6hxfym8z5dbzv08yn31p24fnmw2gisari"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libsmartcols-2.31-r0.apk
  ; sha256 = "131vxdxmib01cc1x7gg3wf2smhy8p5dism99q70mmicxslzsixvy"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xcb-proto-1.12-r1.apk
  ; sha256 = "0qzqzf0dd085n9cs09z3b8c446rrnq1jv0jzhfpxp4ml0bpnq2j5"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xkeyboard-config-2.22-r0.apk
  ; sha256 = "19pmb635dl6zhmkfib3inasx2jp9hm9vrbhnq834sbfc4nq3p4ml"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxxf86vm-1.1.4-r1.apk
  ; sha256 = "191y1p701nx9rd3x24w07dxiwrmpwhyqx017zg4zj2a661dr102p"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxdmcp-dev-1.1.2-r4.apk
  ; sha256 = "1kipss4lq9f0vqka8kscc2641yjb5j3wf4di629j1vflx8vjzbr1"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mkfontdir-1.0.7-r1.apk
  ; sha256 = "1f77ry8bmnpgv6ilnhrb565dbjpbdlpjr8vpm4wvawlbdhjak9b9"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/ncurses-terminfo-base-6.0_p20171125-r0.apk
  ; sha256 = "0vrm0538davp54irspb4140k5fbsxgyads827ng79ipg788akdd2"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mkfontscale-1.1.2-r1.apk
  ; sha256 = "1575q8nhqacnid3hs6y9dsk1lcc5awwwb5g9mvmlsyqmxib3xajj"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xextproto-7.3.0-r2.apk
  ; sha256 = "1q5fsvw6pq70c4b2l7p2idzjb21znw98qkd1m8d0siv354i28h3d"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xtrans-1.3.5-r1.apk
  ; sha256 = "0fygkkjh7hy86ny7p3ic5gx8nlabx3gj8giwdvv4xkpr4idxms92"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libunistring-0.9.7-r0.apk
  ; sha256 = "1w6phzysnj7p3gn5b0h4xnqwa736zgxrzpmza8whb2qc8a920xay"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/expat-2.2.5-r0.apk
  ; sha256 = "0gwysh56byffd4cmqa1pir5j24bwgiv03z2k8fn3yi30lyddc1ir"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/help2man-1.47.5-r0.apk
  ; sha256 = "1ilzm7ni7d25vgd9zmjj550mqmhp72k50p3m9x7284zsyiw6za2g"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/findmnt-2.31-r0.apk
  ; sha256 = "1is584c9nlrp5nkzmxvrzqffp9s6yd3b51gh9dxviqc76imk8vl3"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mcookie-2.31-r0.apk
  ; sha256 = "039pbb19f9jw0w1xd6lnji9chr919l2544521mm1n1zk8mm7dy6s"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/pixman-0.34.0-r3.apk
  ; sha256 = "1qxmfarma3gb8mgsfr2ws15hyp7d6ssxbxgl45146b1vr2vmhk8x"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/font-alias-1.0.3-r1.apk
  ; sha256 = "157n5m3vy0kh7v53jls90bahh8pr4yr5p38dmxdj7d54h2pqzyjk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libintl-0.19.8.1-r1.apk
  ; sha256 = "19ckyy7lsk9y8385nfhiwalkx1bn2y60g2hyj33faplg73yyib20"; }
]
