#!/usr/bin/env bash
set -euxo pipefail

# Integration tests

INTEGRATION_TEST_DIR="$(dirname "$(realpath "$0")")/integration"

for TEST_DEF in $(ls "$INTEGRATION_TEST_DIR"/*.nix); do
  NIXPKGS_ALLOW_UNFREE=1 nix-build "$TEST_DEF"
done

# Kiosk browser

pushd "$(dirname "$(realpath "$0")")/../kiosk"
nix-shell --run bin/test
popd

# Ocaml tests
pushd "$(dirname "$(realpath "$0")")/../controller"
nix-shell --run 'dune test -f --no-buffer'
popd
