# This file was automatically generated by apk2nix on Tue Aug 14 09:42:21 CEST 2018
# Command: /nix/store/2zbqzd3qzl97kjwkib4qiv5wia2cn5ks-apk2nix/bin/apk2nix -o system/apks.nix alpine-base linux-hardened gummiboot xorg-server xf86-video-vesa xf86-input-evdev xf86-input-mouse xf86-input-keyboard udev xinit xf86-video-intel
[

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/cryptsetup-libs-1.7.5-r1.apk
  ; sha256 = "0gw5d87yzdzzrdj3fwqqnwjn2d2khczjk9wl66kplz0q3lsksrxk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/freetype-2.8.1-r3.apk
  ; sha256 = "0czpmascqh6i819v0w7qbqahylsqqkkv1arrdfynfdvpc72ylckg"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xmodmap-1.0.9-r2.apk
  ; sha256 = "0264y633q8j5zj54qglf5pmw3yz1ncxpqvskkn7fpghj6m8yf04x"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mesa-gbm-17.2.4-r1.apk
  ; sha256 = "0pli7f51aa3nk5c7rpgkhlqsnwy5j010mmll4a3p1jb59rqr4s3d"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/zlib-1.2.11-r1.apk
  ; sha256 = "124m1ncl7rs48dp5pa35a831fvgh322b554vmfqm3jpddawgv4ql"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxv-1.0.11-r1.apk
  ; sha256 = "19949644xi7fx2nxikdv74zvrp4wgix6h9rs45rvdzjaslaj5yb7"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxshmfence-1.2-r2.apk
  ; sha256 = "0f4jpw1qssdx96xlmdq3abvpm6x53fy53ibjw72k67g5gn7sfxi8"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/device-mapper-libs-2.02.175-r0.apk
  ; sha256 = "0p7g167caap7p2cmhjia39njkcdb825yfk63zv1m63jjgsz0si5c"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/linux-firmware-20171121-r0.apk
  ; sha256 = "0d09ahgcmxx9ycmv8mp1k7f4ynqi1p7g7ddr65salcqba8w0v1an"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libstdc++-6.4.0-r5.apk
  ; sha256 = "0l5jfbn9kcvjw6miy4gbzgfnfz2injkqvq7dqv7v30ydcnfx4i6n"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libressl2.6-libssl-2.6.5-r0.apk
  ; sha256 = "1xkvzhr1bwicj76ffsvzmpz2440ani03dgm70c10sxhhhaaqdq1s"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xrdb-1.1.0-r2.apk
  ; sha256 = "1gi2ad1dvprsbv6szdrk34v8nx60zld2kblii9ygsa1imqwc61a5"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/wayland-libs-client-1.14.0-r2.apk
  ; sha256 = "0jygqc89bmxhy9w765vrnp87mdk64pfdb13zyksz8sz0vh3658nv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xf86-input-keyboard-1.9.0-r0.apk
  ; sha256 = "1vfls8y2nyms9xmp89asza3xsddyrhp1qmnwvg6x1d8z5bj26cl5"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxt-1.1.5-r1.apk
  ; sha256 = "0kr5x8iyrkxcizws1v59kqz687xidhij7jk5q5b833any73kcynp"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xf86-input-evdev-2.10.5-r0.apk
  ; sha256 = "1h31gp3bci30861260y9ij7izs9r6i90b300cjaphw296n9fdyvk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libpng-1.6.34-r1.apk
  ; sha256 = "16hwbs98nkzsxw5722jxs61cnvqisgai0xqmvh673yx8ij6zqb4b"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libmount-2.31-r0.apk
  ; sha256 = "0wl89nfhvpddqx21lsq17d1iawkh14kcj14gxhhw5wp8mc9k2cnv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxfont2-2.0.3-r0.apk
  ; sha256 = "134v0rxk7my22s03qkkx1dfsii0838qnyis2vhaazlwi2wrgbv2k"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/gummiboot-48.1-r0.apk
  ; sha256 = "0iy1zm1p9cwqsdixfs91yv0hfz30cxy7mq6hjv2fkgwrz714ksia"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-conf-3.7.0-r1.apk
  ; sha256 = "1qcd9a31ikrr2cr8liw4xa5xkxqzjwf39pwlqqd70w4xgpkpcnl6"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mesa-dri-intel-17.2.4-r1.apk
  ; sha256 = "0b4hj5lxwm7sw6l3bb3i5571dgpf7lqh5vk9w1f06yrkhp6ic1qf"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/wayland-libs-cursor-1.14.0-r2.apk
  ; sha256 = "0csypwmrg2lr3x2f9h4q572v3x2q3q9lprchnx8ggz1c89wln3xg"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libevdev-1.5.7-r1.apk
  ; sha256 = "04d4piffrjy92maalfdxxccgh68119gvnjpclmvzbgv1pz9zhmh1"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/busybox-initscripts-3.1-r2.apk
  ; sha256 = "0qdhq7v8bqkcfkg6d53gkbylx1g0vpkdbxbf0497vq7fmdmzsz73"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/encodings-1.0.4-r1.apk
  ; sha256 = "0blx22js6amzwsy2vy5l4mq8jmw68wqapb67zfyrymp16d8wgzjr"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libice-1.0.9-r2.apk
  ; sha256 = "1nly41xif2nkiplgaakbvwnfbarkl4zfh1kmnrbj0pifmyj7spbn"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxfixes-5.0.3-r1.apk
  ; sha256 = "08ip4qzzdyfc9d6lhbl3nff1dqw7n23rvhmwy2cz9bbqiq2r779p"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxmu-1.1.2-r1.apk
  ; sha256 = "1sb9nj8hy8l404nnp84m8rpn1nl2pask5yl177rv2wq849lzg7xh"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libfontenc-1.1.3-r2.apk
  ; sha256 = "0dskr06246ycxgcasnrp34jj4sdi5a56zk820dz7zczkglivcf3v"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xf86-video-intel-2.99.917_git20170325-r0.apk
  ; sha256 = "0xxsp607gg94q4bb2sqvkpzw38z7v72ap8131z0amhvnrvwrvsv0"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxdmcp-1.1.2-r4.apk
  ; sha256 = "0h28p3rzaccs17sdy8vd7mjb9n4501xc5vv3agphjipkrna16qij"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mcpp-2.7.2-r1.apk
  ; sha256 = "07jxc0hcdv30yymg9bvp1fq9pj8ads0ghr4k4z64ivj9yh61437l"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xcb-util-0.4.0-r1.apk
  ; sha256 = "1sy4ibb084sgf16zdkcjxbdmrr60iri8zbqyhh4phc776ld9byg0"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxcb-1.12-r1.apk
  ; sha256 = "0jdld4gqsla96grpczw1ihmz5jb4g228lby8hpbqh9401425hk50"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxau-1.0.8-r2.apk
  ; sha256 = "1nxv9bc0srdz0fz1lar0pnjm13bhhx9ajc7qw4fh88r8l46pbxlq"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/eudev-3.2.4-r1.apk
  ; sha256 = "0qrkyr91hldbqawqrnck4xqnvvi841xpcxdyvyiy9n3rx1k1qpxl"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libffi-3.2.1-r4.apk
  ; sha256 = "0hh403fwv20lgl6dls63a53g5hi67pmjd3wrlvkphbii0vhi6nsr"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxvmc-1.0.10-r1.apk
  ; sha256 = "0q7va9zdnnm0i1my2i1j01vjhigrngg7qxvs435cxz8rzk010xhh"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/font-cursor-misc-1.0.3-r1.apk
  ; sha256 = "1lvp29cm3bvn09xssbpqiivm5p637dw8xvkbi2m7m5nb4n1prhzc"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libbz2-1.0.6-r6.apk
  ; sha256 = "00d8sdnjam99690nsgq50ccx99kvxn9n8vvq97295n91fg4phd9b"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/busybox-suid-1.27.2-r11.apk
  ; sha256 = "06v9g8f2dlngnfqxrk6n7pjr4i8fgi5y80f49g76dfwp2bz93s3r"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/font-misc-misc-1.1.2-r1.apk
  ; sha256 = "19sx5zdvmakpk4qavh3x18zavnvkap9ga1c7mb6rkswg21ss7kza"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxdamage-1.1.4-r1.apk
  ; sha256 = "0cam8g3z22gplbi1a7gy3wgx1m4s2ll080jmr8693cnyqhmkyvvc"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/eudev-libs-3.2.4-r1.apk
  ; sha256 = "1nzm8f3mp34pn6bpndmcpb2k4r05n8jv318hvs8gxixwxqy4n8dz"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mesa-gl-17.2.4-r1.apk
  ; sha256 = "0bfk290ra7g1ncjbx0nswh28f77b6xhrd9vvvswf9fi7fpdkppnd"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libuuid-2.31-r0.apk
  ; sha256 = "08cmxfrkbb5r217qcag2frp70knck7ncxi484ab95xm5vaw7qwhk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libepoxy-1.4.3-r1.apk
  ; sha256 = "1ryxqzgi7mina21b32x3695dgb7xgsgj8pzmpcsi615lv0rb7i0b"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxext-1.3.3-r2.apk
  ; sha256 = "1178sg2ahkdhh0w01kxj1k9i5z6i9m6iziv42a7hl4m2gs5yvyhp"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xauth-1.0.10-r1.apk
  ; sha256 = "1x9k4ahw96w6nwb29rsakz731sylifx9kbfnxhhaksmvi7wx7vxy"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xf86-video-vesa-2.3.4-r2.apk
  ; sha256 = "0miapzyq40hnaj263a67mjirhghs2nvd0b1m3zv8sbgdkn639chx"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libx11-1.6.5-r1.apk
  ; sha256 = "1f8amk5c6vby66b34swvbbjiw0cn5fxsr8yrn8594x3z1a1jm2z5"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/busybox-1.27.2-r11.apk
  ; sha256 = "1b37bil28gpnb8p4wzlw08a9i82ajckzq1nm7n9xw3npyfqvlbv6"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mesa-glapi-17.2.4-r1.apk
  ; sha256 = "1j4jdsn776pwb3s2gy3m545c7qvq0in9b52sjsvz5mw5mahx5lby"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/wayland-libs-server-1.14.0-r2.apk
  ; sha256 = "1kjywpyd83vmbhh0g898y95xb459psc7r8kjmzqyssr8lk07bjjz"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-base-3.7.0-r0.apk
  ; sha256 = "05k25lwa2l2gn1wiiqgb7sgrwrn2biccixqjn6ppkcilbwsw4v7l"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/musl-utils-1.1.18-r3.apk
  ; sha256 = "1yvcjr2rc8yl85y9r5pyyywdpv1nb8i6qizslf5h2ij2nm26ywid"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/musl-1.1.18-r3.apk
  ; sha256 = "1vjj1kjqwldd313k74qczy3vslrfhpbgyycx1qfys8jbcdf2wljk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xorg-server-1.19.5-r0.apk
  ; sha256 = "0aiz8bkqpb8adyv9w56w0p1pd8q01lzj2arv507d31s329hswnlz"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xz-libs-5.2.3-r1.apk
  ; sha256 = "19axnwgmfmcb9csc8yss2dqy7i35za2gcmq9v7610k8rzprdj0gl"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libressl2.6-libtls-2.6.5-r0.apk
  ; sha256 = "15xcda4y4563nw0zckl4wvgv5x5syr69jf9cnpk4ikd7mh4kyffk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-baselayout-3.0.5-r2.apk
  ; sha256 = "1pxh2kmsj8zn92wh4kpsi1lk3314glwinrihqi4zrs91qn81bdi0"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mcpp-libs-2.7.2-r1.apk
  ; sha256 = "0s85935mf9kz02zd8v3rnffd7hmydarypjvf59qif03z171i17ab"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxkbfile-1.0.9-r2.apk
  ; sha256 = "08wikv0zj83hnhgza6qyfg4b7x1qp27ciqali6g689sfj8s50k2n"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xf86-input-mouse-1.9.2-r0.apk
  ; sha256 = "1qqhjgqzh06389gk4j4zidmzidgzw96jqqnpc5xwr47bsinivnrg"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libsm-1.2.2-r1.apk
  ; sha256 = "0nq6cpxf4i5dmdhavl9wvm0w8wzc43wx573356qg5k1wpii2cj51"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xinit-1.3.4-r1.apk
  ; sha256 = "1arzaazxwn1y8f5nw5r87y22xanwcci4yvlr58gv3wx9iy2kh4nv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libblkid-2.31-r0.apk
  ; sha256 = "0a99187bns2mvrj7gk107j0nddzhc4cmxryr2pk9412jman8kpgd"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/kmod-24-r0.apk
  ; sha256 = "1giglgrlypydcy8sch7rlv7mdg13q6kwlbhyfqddqqxxzlma3pj3"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/udev-init-scripts-32-r1.apk
  ; sha256 = "1gfyx89y40766dmp0hik6p1wb2523za9lk80gp5wlrjyc5qv40c9"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libcrypto1.0-1.0.2o-r1.apk
  ; sha256 = "02k67ih679y73zl5q6y54vdvwxlrcyvykjy23dyc5j2qqfzssah1"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/apk-tools-2.9.1-r2.apk
  ; sha256 = "1cyx15677xx7m37frqs6aa7iqn1g34wmpasa7yi3b1djdrvq19yv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/linux-hardened-4.9.65-r1.apk
  ; sha256 = "1l3hq7djzm5qn6cp8hlkp6722miypsmzszavlipdfd55f6z6csfr"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xkbcomp-1.4.0-r2.apk
  ; sha256 = "01f3xcy1lb90pcnxvzsnglbjr5wbfg1yz53f50nn2hni0k0jm1a8"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libpciaccess-0.13.5-r1.apk
  ; sha256 = "1akl82lgzmsm0kyck2bn1cf7a8x1xdcjxskf7wq7ddl8q7svzxgh"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/util-macros-1.19.1-r1.apk
  ; sha256 = "177y0yjxjk8ic2rd07dxykwqwxmra00lyv5wiz2m11sq60bhcgm3"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libbsd-0.8.6-r1.apk
  ; sha256 = "1q0kmb24i7x1s2ild9020phxin7xrvdh7ac5cjp2njdaz33m8qkg"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libgcc-6.4.0-r5.apk
  ; sha256 = "1146gmvgyykq3whfypzm9y424zis12myflxxca3l7fmzq2zilwv2"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libdrm-2.4.88-r0.apk
  ; sha256 = "1l407cjh9g8hd2ym4p2izga98q1lmh1hpr2rl6p53wpkdvpdbmr6"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/scanelf-1.2.2-r1.apk
  ; sha256 = "1n6s8grkskia2bfxy94bkhnvcqp0bm2m3n6lnwiq49rl3aa3myhl"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/fontconfig-2.12.6-r0.apk
  ; sha256 = "012qyg30krky6x1wbcl6hxfym8z5dbzv08yn31p24fnmw2gisari"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libsmartcols-2.31-r0.apk
  ; sha256 = "131vxdxmib01cc1x7gg3wf2smhy8p5dism99q70mmicxslzsixvy"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/lddtree-1.26-r1.apk
  ; sha256 = "1z1fpx9xjp4fcqlk4acm5wsng4gg9v5vd8rkvspk5fydyhyqdclw"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/xkeyboard-config-2.22-r0.apk
  ; sha256 = "19pmb635dl6zhmkfib3inasx2jp9hm9vrbhnq834sbfc4nq3p4ml"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libc-utils-0.7.1-r0.apk
  ; sha256 = "19gv1vhvjd0lzyjzqdq1j04cjz5kq9warak349jvk0932yb3j74l"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libxxf86vm-1.1.4-r1.apk
  ; sha256 = "191y1p701nx9rd3x24w07dxiwrmpwhyqx017zg4zj2a661dr102p"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mkfontdir-1.0.7-r1.apk
  ; sha256 = "1f77ry8bmnpgv6ilnhrb565dbjpbdlpjr8vpm4wvawlbdhjak9b9"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/openrc-0.24.1-r4.apk
  ; sha256 = "0r7qsbjljhxgdkgrcqsl8jal7y75dwjcim2kf9l7gdbinsnvrca3"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mkfontscale-1.1.2-r1.apk
  ; sha256 = "1575q8nhqacnid3hs6y9dsk1lcc5awwwb5g9mvmlsyqmxib3xajj"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mtdev-1.1.5-r1.apk
  ; sha256 = "1r10c2anxnb9hg6c1s6dwl3ippv4xn4q1yjr4fys7a2g8zxa7q53"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/expat-2.2.5-r0.apk
  ; sha256 = "0gwysh56byffd4cmqa1pir5j24bwgiv03z2k8fn3yi30lyddc1ir"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/libressl2.6-libcrypto-2.6.5-r0.apk
  ; sha256 = "1b8v18s054wqh54b0vwghcn52q01nzxfw3vi6ab0qaj6jywclzrs"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/ssl_client-1.27.2-r11.apk
  ; sha256 = "179cv4wmn6v1411v7wcazr1z9qiv9kz5q1p1q681v90h91rckn11"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/findmnt-2.31-r0.apk
  ; sha256 = "1is584c9nlrp5nkzmxvrzqffp9s6yd3b51gh9dxviqc76imk8vl3"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mcookie-2.31-r0.apk
  ; sha256 = "039pbb19f9jw0w1xd6lnji9chr919l2544521mm1n1zk8mm7dy6s"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/pixman-0.34.0-r3.apk
  ; sha256 = "1qxmfarma3gb8mgsfr2ws15hyp7d6ssxbxgl45146b1vr2vmhk8x"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/font-alias-1.0.3-r1.apk
  ; sha256 = "157n5m3vy0kh7v53jls90bahh8pr4yr5p38dmxdj7d54h2pqzyjk"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/alpine-keys-2.1-r1.apk
  ; sha256 = "1isw8wd7w0k2jyx76x77051560myaliw4pbq97p8wk1j02d1wbbv"; }

  { url = http://dl-cdn.alpinelinux.org/alpine/v3.7/main/x86_64/mkinitfs-3.2.0-r4.apk
  ; sha256 = "0yi230xbvg4widh05ii1i9199nmrirw41qis4cb940rwrda5hhwa"; }
]
