name: "Test"
on:
  pull_request:
  push:
jobs:
  build-something:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - uses: ./.github/actions/prep-build-env
      secrets: inherit
    - run: NIXPKGS_ALLOW_UNFREE=1 nix-build testing/integration/rauc-statusfile-recovery.nix
