name: "Prepare nix build environment"
runs:
  using: "composite"
  steps:
  - name: Ensure KVM is usable by nix-build
    run: sudo chmod a+rwx /dev/kvm
    shell: bash
  - uses: cachix/install-nix-action@v18
    with:
      nix_path: nixpkgs=channel:nixos-unstable
      extra_nix_config: |
        system-features = nixos-test benchmark big-parallel kvm
  - uses: DeterminateSystems/magic-nix-cache-action@v8
